version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    command: php-fpm

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./storage:/var/www/storage
      - ./public:/var/www/public
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: qlbv
      MYSQL_USER: qlbv_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backups/mysql:/backups
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./storage:/var/www/storage
    command: php artisan queue:work redis --sleep=3 --tries=3 --max-time=3600

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./storage:/var/www/storage
    command: php artisan schedule:work

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  qlbv_network:
    driver: bridge 