<?php

return [
    'medicine' => [
        'detect_keys' => ['MA_THUOC', 'TEN_THUOC', 'SO_DANG_KY'], // Các cột key để nhận diện loại catalog
        'mapping' => [
            'ma_thuoc' => ['MA_THUOC', 'Mã thuốc', 'MA THUOC'],
            'ten_hoat_chat' => ['TEN_HOAT_CHAT', 'Tên hoạt chất', 'TEN HOAT CHAT'],
            'ten_thuoc' => ['TEN_THUOC', 'Tên thuốc', 'TEN THUOC'],
            'don_vi_tinh' => ['DON_VI_TINH', 'Đơn vị tính', 'DON VI TINH'],
            'ham_luong' => ['HAM_LUONG', 'Hàm lượng', 'HAM LUONG'],
            'duong_dung' => ['DUONG_DUNG', 'Đường dùng', 'DUONG DUNG'],
            'ma_duong_dung' => ['MA_DUONG_DUNG', 'Mã đường dùng', 'MA DUONG DUNG'],
            'dang_bao_che' => ['DANG_BAO_CHE', 'Dạng bào chế', 'DANG BAO CHE'],
            'so_dang_ky' => ['SO_DANG_KY', 'Số đăng ký', 'SO DANG KY'],
            'so_luong' => ['SO_LUONG', 'Số lượng', 'SO LUONG'],
            'don_gia' => ['DON_GIA', 'Đơn giá', 'DON GIA'],
            'don_gia_bh' => ['DON_GIA_BH', 'Đơn giá BHYT', 'DON GIA BH'],
            'quy_cach' => ['QUY_CACH', 'Quy cách', 'QUY CACH'],
            'nha_sx' => ['NHA_SX', 'Nhà sản xuất', 'NHA SX'],
            'nuoc_sx' => ['NUOC_SX', 'Nước sản xuất', 'NUOC SX'],
            'nha_thau' => ['NHA_THAU', 'Nhà thầu', 'NHA THAU'],
            'tt_thau' => ['TT_THAU', 'TT thầu', 'TT THAU'],
            'tu_ngay' => ['TU_NGAY', 'Từ ngày', 'TU NGAY'],
            'den_ngay' => ['DEN_NGAY', 'Đến ngày', 'DEN NGAY'],
            'ma_cskcb' => ['MA_CSKCB', 'Mã CSKCB', 'MA CSKCB'],
            'loai_thuoc' => ['LOAI_THUOC', 'Loại thuốc', 'LOAI THUOC'],
            'loai_thau' => ['LOAI_THAU', 'Loại thầu', 'LOAI THAU'],
            'ht_thau' => ['HT_THAU', 'HT thầu', 'HT THAU'],
        ],
        'required_fields' => ['ma_thuoc', 'ten_thuoc', 'ham_luong', 'so_dang_ky', 'tt_thau', 'tu_ngay'],
        'unique_keys' => ['ma_thuoc', 'ten_thuoc', 'ham_luong', 'so_dang_ky', 'don_gia_bh', 'tt_thau', 'tu_ngay'],
    ],

    'medical_supply' => [
        'detect_keys' => ['MA_VAT_TU', 'TEN_VAT_TU', 'NHOM_VAT_TU'],
        'mapping' => [
            'ma_vat_tu' => ['MA_VAT_TU', 'Mã vật tư', 'MA VAT TU'],
            'nhom_vat_tu' => ['NHOM_VAT_TU', 'Nhóm vật tư', 'NHOM VAT TU'],
            'ten_vat_tu' => ['TEN_VAT_TU', 'Tên vật tư', 'TEN VAT TU'],
            'ma_hieu' => ['MA_HIEU', 'Mã hiệu', 'MA HIEU'],
            'quy_cach' => ['QUY_CACH', 'Quy cách', 'QUY CACH'],
            'hang_sx' => ['HANG_SX', 'Hãng sản xuất', 'HANG SX'],
            'nuoc_sx' => ['NUOC_SX', 'Nước sản xuất', 'NUOC SX'],
            'don_vi_tinh' => ['DON_VI_TINH', 'Đơn vị tính', 'DON VI TINH'],
            'don_gia' => ['DON_GIA', 'Đơn giá', 'DON GIA'],
            'don_gia_bh' => ['DON_GIA_BH', 'Đơn giá BHYT', 'DON GIA BH'],
            'tyle_tt_bh' => ['TYLE_TT_BH', 'Tỷ lệ TT BHYT', 'TYLE TT BH'],
            'so_luong' => ['SO_LUONG', 'Số lượng', 'SO LUONG'],
            'dinh_muc' => ['DINH_MUC', 'Định mức', 'DINH MUC'],
            'nha_thau' => ['NHA_THAU', 'Nhà thầu', 'NHA THAU'],
            'tt_thau' => ['TT_THAU', 'TT thầu', 'TT THAU'],
            'tu_ngay' => ['TU_NGAY', 'Từ ngày', 'TU NGAY'],
            'den_ngay_hd' => ['DEN_NGAY_HD', 'Đến ngày HĐ', 'DEN NGAY HD'],
            'ma_cskcb' => ['MA_CSKCB', 'Mã CSKCB', 'MA CSKCB'],
            'loai_thau' => ['LOAI_THAU', 'Loại thầu', 'LOAI THAU'],
            'ht_thau' => ['HT_THAU', 'HT thầu', 'HT THAU'],
            'den_ngay' => ['DENNGAY', 'Đến ngày', 'DEN NGAY'],
        ],
        'required_fields' => ['ma_vat_tu', 'nhom_vat_tu', 'ten_vat_tu', 'tt_thau', 'don_gia', 'don_gia_bh', 'tu_ngay'],
        'unique_keys' => ['ma_vat_tu', 'ten_vat_tu', 'tt_thau', 'don_gia_bh', 'tu_ngay'],
    ],

    'service' => [
        'detect_keys' => ['MA_TUONG_DUONG', 'TEN_DVKT_PHEDUYET', 'TEN_DVKT_GIA'],
        'mapping' => [
            'ma_dich_vu' => ['MA_TUONG_DUONG', 'Mã tương đương', 'MA TUONG DUONG'],
            'ten_dich_vu' => ['TEN_DVKT_PHEDUYET', 'Tên DVKT phê duyệt', 'TEN DVKT PHEDUYET', 'TEN_DVKT_GIA', 'Tên DVKT giá'],
            'don_gia' => ['DON_GIA', 'Đơn giá', 'DON GIA'],
            'quy_trinh' => ['QUYET_DINH', 'Quyết định', 'QUYET DINH'],
            'tu_ngay' => ['TUNGAY', 'Từ ngày', 'TU NGAY'],
            'den_ngay' => ['DENNGAY', 'Đến ngày', 'DEN NGAY'],
        ],
        'required_fields' => ['ma_dich_vu', 'ten_dich_vu', 'don_gia', 'tu_ngay'],
        'unique_keys' => ['ma_dich_vu', 'ten_dich_vu', 'don_gia', 'quy_trinh', 'tu_ngay'],
    ],

    'medical_staff' => [
        'detect_keys' => ['MA_BHXH', 'HO_TEN', 'MA_KHOA'],
        'mapping' => [
            'ma_loai_kcb' => ['MA_LOAI_KCB', 'Mã loại KCB', 'MA LOAI KCB'],
            'ma_khoa' => ['MA_KHOA', 'Mã khoa', 'MA KHOA'],
            'ten_khoa' => ['TEN_KHOA', 'Tên khoa', 'TEN KHOA'],
            'ma_bhxh' => ['MA_BHXH', 'Mã BHXH', 'MA BHXH'],
            'ho_ten' => ['HO_TEN', 'Họ tên', 'HO TEN'],
            'gioi_tinh' => ['GIOI_TINH', 'Giới tính', 'GIOI TINH'],
            'chucdanh_nn' => ['CHUCDANH_NN', 'Chức danh NN', 'CHUCDANH NN'],
            'vi_tri' => ['VI_TRI', 'Vị trí', 'VI TRI'],
            'macchn' => ['MACCHN', 'Mã CCHN', 'MA CCHN'],
            'ngaycap_cchn' => ['NGAYCAP_CCHN', 'Ngày cấp CCHN', 'NGAYCAP CCHN'],
            'noicap_cchn' => ['NOICAP_CCHN', 'Nơi cấp CCHN', 'NOICAP CCHN'],
            'phamvi_cm' => ['PHAMVI_CM', 'Phạm vi CM', 'PHAMVI CM'],
            'phamvi_cmbs' => ['PHAMVI_CMBS', 'Phạm vi CMBS', 'PHAMVI CMBS'],
            'dvkt_khac' => ['DVKT_KHAC', 'DVKT khác', 'DVKT KHAC'],
            'vb_phancong' => ['VB_PHANCONG', 'VB phân công', 'VB PHANCONG'],
            'thoigian_dk' => ['THOIGIAN_DK', 'Thời gian ĐK', 'THOIGIAN DK'],
            'thoigian_ngay' => ['THOIGIAN_NGAY', 'Thời gian ngày', 'THOIGIAN NGAY'],
            'thoigian_tuan' => ['THOIGIAN_TUAN', 'Thời gian tuần', 'THOIGIAN TUAN'],
            'cskcb_khac' => ['CSKCB_KHAC', 'CSKCB khác', 'CSKCB KHAC'],
            'cskcb_cgkt' => ['CSKCB_CGKT', 'CSKCB CGKT', 'CSKCB CGKT'],
            'qd_cgkt' => ['QD_CGKT', 'QD CGKT', 'QD CGKT'],
            'tu_ngay' => ['TU_NGAY', 'Từ ngày', 'TU NGAY'],
            'den_ngay' => ['DEN_NGAY', 'Đến ngày', 'DEN NGAY'],
        ],
        'required_fields' => ['ma_khoa', 'ten_khoa', 'ma_bhxh', 'ho_ten', 'chucdanh_nn', 'macchn', 'ngaycap_cchn', 'noicap_cchn', 'thoigian_dk', 'tu_ngay'],
        'unique_keys' => ['ma_bhxh'],
    ],

    'department_bed' => [
        'detect_keys' => ['MA_KHOA', 'TEN_KHOA', 'GIUONG_PD'],
        'mapping' => [
            'ma_loai_kcb' => ['MA_LOAI_KCB', 'Mã loại KCB', 'MA LOAI KCB'],
            'ma_khoa' => ['MA_KHOA', 'Mã khoa', 'MA KHOA'],
            'ten_khoa' => ['TEN_KHOA', 'Tên khoa', 'TEN KHOA'],
            'ban_kham' => ['BAN_KHAM', 'Bàn khám', 'BAN KHAM'],
            'giuong_pd' => ['GIUONG_PD', 'Giường PD', 'GIUONG PD'],
            'giuong_2015' => ['GIUONG_2015', 'Giường 2015', 'GIUONG 2015'],
            'giuong_tk' => ['GIUONG_TK', 'Giường TK', 'GIUONG TK'],
            'giuong_hstc' => ['GIUONG_HSTC', 'Giường HSTC', 'GIUONG HSTC'],
            'giuong_hscc' => ['GIUONG_HSCC', 'Giường HSCC', 'GIUONG HSCC'],
            'ldlk' => ['LDLK', 'LDLK'],
            'lien_khoa' => ['LIEN_KHOA', 'Liên khoa', 'LIEN KHOA'],
            'den_ngay' => ['DEN_NGAY', 'Đến ngày', 'DEN NGAY'],
        ],
        'required_fields' => ['ma_khoa', 'ten_khoa'],
        'unique_keys' => ['ma_khoa'],
    ],

    'equipment' => [
        'detect_keys' => ['TEN_TB', 'MA_MAY', 'KY_HIEU'],
        'mapping' => [
            'ten_tb' => ['TEN_TB', 'Tên TB', 'TEN TB'],
            'ky_hieu' => ['KY_HIEU', 'Ký hiệu', 'KY HIEU'],
            'congty_sx' => ['CONGTY_SX', 'Công ty SX', 'CONGTY SX'],
            'nuoc_sx' => ['NUOC_SX', 'Nước SX', 'NUOC SX'],
            'nam_sx' => ['NAM_SX', 'Năm SX', 'NAM SX'],
            'nam_sd' => ['NAM_SD', 'Năm SD', 'NAM SD'],
            'ma_may' => ['MA_MAY', 'Mã máy', 'MA MAY'],
            'so_luu_hanh' => ['SO_LUU_HANH', 'Số lưu hành', 'SO LUU HANH'],
            'hd_tu' => ['HD_TU', 'HD từ', 'HD TU'],
            'hd_den' => ['HD_DEN', 'HD đến', 'HD DEN'],
            'tu_ngay' => ['TU_NGAY', 'Từ ngày', 'TU NGAY'],
            'den_ngay' => ['DEN_NGAY', 'Đến ngày', 'DEN NGAY'],
        ],
        'required_fields' => ['ten_tb', 'ky_hieu', 'ma_may', 'congty_sx', 'nuoc_sx', 'nam_sx', 'nam_sd', 'so_luu_hanh'],
        'unique_keys' => ['ma_may'],
    ],

    'administrative_unit' => [
        'detect_keys' => ['Tỉnh Thành Phố', 'Mã TP', 'Quận Huyện'],
        'mapping' => [
            'province_name' => ['Tỉnh Thành Phố', 'Tỉnh/Thành phố'],
            'province_code' => ['Mã TP', 'Mã tỉnh', 'Mã TP'],
            'district_name' => ['Quận Huyện', 'Quận/Huyện'],
            'district_code' => ['Mã QH', 'Mã quận huyện', 'Mã QH'],
            'commune_name' => ['Phường Xã', 'Phường/Xã'],
            'commune_code' => ['Mã PX', 'Mã phường xã', 'Mã PX'],
        ],
        'required_fields' => ['province_name', 'province_code', 'district_name', 'district_code', 'commune_name', 'commune_code'],
        'unique_keys' => ['commune_code'],
    ],

    'medical_organization' => [
        'detect_keys' => ['Mã', 'Tên', 'Tuyến CMKT'],
        'mapping' => [
            'ma_cskcb' => ['Mã', 'Mã CSKCB'],
            'ten_cskcb' => ['Tên', 'Tên CSKCB'],
            'tuyen_cmkt' => ['Tuyến CMKT', 'Tuyến chuyên môn kỹ thuật'],
            'hang_benh_vien' => ['Hạng bệnh viện', 'Hạng BV'],
            'dia_chi_cskcb' => ['Địa chỉ', 'Địa chỉ CSKCB'],
        ],
        'required_fields' => ['ma_cskcb', 'ten_cskcb', 'tuyen_cmkt', 'hang_benh_vien', 'dia_chi_cskcb'],
        'unique_keys' => ['ma_cskcb'],
    ],

    'job_categories' => [
        'detect_keys' => ['MA_NGHE_NGHIEP', 'TEN_NGHE_NGHIEP'],
        'mapping' => [
            'job_code' => ['MA_NGHE_NGHIEP', 'Mã nghề nghiệp', 'MA NGHE NGHIEP'],
            'job_name' => ['TEN_NGHE_NGHIEP', 'Tên nghề nghiệp', 'TEN NGHE NGHIEP'],
        ],
        'required_fields' => ['job_code', 'job_name'],
        'unique_keys' => ['job_code'],
    ],
];

